### ISSUE TITLE
BINGO plot crashes with linear=True

### ISSUE THREAD

**Issue by dpshelio** [sunpy/radiospectra#1]
_From @segfaulthunter on August 20, 2013 9:1_

_Copied from original issue: sunpy/sunpy#546_

**Comment by dpshelio** [comment]
_From @Cadair on May 28, 2014 22:39_

@segfaulthunter You don't happen to have time to patch this in the next week do you?

**Comment by dpshelio** [comment]
_From @wafels on May 30, 2014 13:24_

What is a BINGO plot?

**Comment by dpshelio** [comment]
_From @Cadair on May 30, 2014 13:35_

no idea, I guess it is in spectra somewhere :p

**Comment by dpshelio** [comment]
BINGO is one of the CALLISTO observatories.

**Comment by dpshelio** [comment]
_From @wafels on May 31, 2014 15:47_

Thanks!  I found it here:

http://e-callisto.org/coverage/coverage.html

**Comment by nabobalis** [comment]
Deleted Spectrogram class and started again.
