### ISSUE TITLE
Spectrum class should check that freq and data are same dimension on creation

### ISSUE THREAD

**Issue by dpshelio** [sunpy/radiospectra#14]
_From @ehsteve on July 18, 2015 17:33_

_Copied from original issue: sunpy/sunpy#1501_

**Comment by dpshelio** [comment]
_From @sudk1896 on October 21, 2015 19:26_

Hi,
I went through the Spectrum class. When you say frequency and data axis dimensions should be same, you mean you want the lengths of both arrays (frequency and data) to be same, If not  then you want to raise an error/exception. Correct me If I am wrong ?
I am assuming the init procedure is creating the data and frequency array in the class. What do you want to do, when the dimensions aren't same ?
I would like to work on this, seems like the ideal beginner task to me.

**Comment by Raahul-Singh** [comment]
What more work is required here?

**Comment by dpshelio** [comment]
A lot.... not just in here, but in the whole library. This will be stuck for a while.

**Comment by nabobalis** [comment]
Deleted Spectrogram class and started again.
