### ISSUE TITLE
Fill in missing lines in top-level README.rst file

### ISSUE THREAD

**Issue by namurphy** [sunpy/radiospectra#17]
The top-level README file currently says:
> If you are coming here from the Warning deprecation in sunpy you more probably need to change from
> ```Python from sunpy.spectra.spectrum import Spectrum```
> to
> after installing it as:

There are lines missing after "to" and "after installing it as:" that need to be filled in.  

Thank you!

**Comment by nabobalis** [comment]
I think this was updated.
