### ISSUE TITLE
Do a release before SunPy 1.0

### ISSUE THREAD

**Issue by Cadair** [sunpy/radiospectra#25]
@nabobalis @dpshelio where are we on this? Does it work with master at the moment? Should we do a release now? Do we have a way of knowing if we break this with sunpy master?

**Comment by nabobalis** [comment]
Yes. Yes if nothing will break in sunpy 1.0 in the last two main PRs. The CI will tell you, we can schedule it?

**Comment by Cadair** [comment]
@nabobalis can you take the conn on getting a release of this out the door? and scheduling a cron with webhook into the infrastructure room?

**Comment by nabobalis** [comment]
Sure and Sure but no room.

**Comment by Cadair** [comment]
Thanks

**Comment by nabobalis** [comment]
Up on PyPi now, feedstock updated.
