### ISSUE TITLE
Callisto query returns double the results

### ISSUE THREAD

**Issue by dpshelio** [sunpy/radiospectra#3]
_From @ehsteve on January 7, 2015 20:21_

The results of the following command

```
result = list(query(
        datetime(2011, 9, 22, 5), datetime(2011, 9, 22, 6), set(["BIR"])
    ))
```

returns duplicates.

_Copied from original issue: sunpy/sunpy#1252_

**Comment by nabobalis** [comment]
Deleted Spectrogram class and started again.
