### ISSUE TITLE
RSTN data access and loading capabilities

### ISSUE THREAD

**Issue by hayesla** [sunpy/radiospectra#50]
### Description
 The Radio Solar Telescope Network (RSTN) is often used by the community, both the 1s fixed frequency data available for 8 frequencies (245, 410, 610 MHz and1.4, 2.7, 5, 8.8, 15.4 GHz) from 4 worldwide networks (Learmonth, San-Vito, Sagmore-Hill, and Paehua) that have different time coverages, and also the dynamic spectra data (25-180MHz) too. 

It would be nice to be able to search for this data and then have readers for the text files for the fixed frequency data and for the binary spectral data files, and radiospectra is probably the best place for this. 

The data is available here:

- Fixed frequency: ftp://ftp.ngdc.noaa.gov/STP/space-weather/solar-data/solar-features/solar-radio/rstn-1-second/

- Dyanmic spectral data: ftp://ftp.ngdc.noaa.gov/STP/space-weather/solar-data/solar-features/solar-radio/rstn-spectral/

Developing a client would be very straight forward, and I already have some readers that can be added here too. 

thoughts?

**Comment by samaloney** [comment]
Hey I totally missed this so this is kinda already done in #44 have added client and specific spectrograms for Callisto, EOVSA, RSTN, SWAVES, PSP review most welcome

**Comment by samaloney** [comment]
Closed in #44
