### ISSUE TITLE
Sunpy_Spectrogram Error in a simple code

### ISSUE THREAD

**Issue by dpshelio** [sunpy/radiospectra#7]
_From @gmlaghari on March 1, 2016 9:47_

Below is my code and I am getting an error on Sunpy 0.6.1

``` python
import matplotlib.pyplot as plt
%matplotlib
import sunpy.spectra
from sunpy.spectra.sources.callisto import CallistoSpectrogram
image = CallistoSpectrogram.read('/home/ghulam/caldata/MUPK_20150822_064500_59.fit')
image.peek()

Using matplotlib backend: Qt4Agg

---------------------------------------------------------------------------
UnicodeDecodeError                        Traceback (most recent call last)
<ipython-input-4-9113c813a1c3> in <module>()
      4 from sunpy.spectra.sources.callisto import CallistoSpectrogram
      5 image = CallistoSpectrogram.read('/home/ghulam/caldata/MUPK_20150822_064500_59.fit')
----> 6 image.peek()

/home/ghulam/anaconda2/lib/python2.7/site-packages/sunpy/spectra/spectrogram.py in peek(self, *args, **kwargs)
    435         """
    436         figure()
--> 437         ret = self.plot(*args, **kwargs)
    438         plt.show()
    439         return ret

/home/ghulam/anaconda2/lib/python2.7/site-packages/sunpy/spectra/spectrogram.py in plot(self, figure, overlays, colorbar, vmin, vmax, linear, showz, yres, max_dist, **matplotlib_args)
    563                 get_day(self.start).strftime("%d %b %Y"),
    564                 'Radio flux density',
--> 565    566             ])
    567         )

UnicodeDecodeError: 'ascii' codec can't decode byte 0xd8 in position 3: ordinal not in range(128)
              '(' + ', '.join(self.instruments) + ')',
```

 Please guide. The plot doesn't show colorbar as well. 

_Copied from original issue: sunpy/sunpy#1687_

**Comment by dpshelio** [comment]
_From @gmlaghari on March 3, 2016 6:39_

How do I know whether you will have fixed this bug or not?

**Comment by dpshelio** [comment]
_From @Cadair on March 3, 2016 9:40_

hey @gmlaghari is it possible you can provide the file you are using so we can recreate the error?

**Comment by dpshelio** [comment]
_From @gmlaghari on March 3, 2016 9:57_

@Cadair Fits file is attached please.
[MUPK_20150822_064500_59.fit.zip](https://github.com/sunpy/sunpy/files/156489/MUPK_20150822_064500_59.fit.zip)

**Comment by dpshelio** [comment]
_From @Cadair on March 3, 2016 10:2_

@gmlaghari I will try and look at it, but I am rather busy at the moment, so I can't promise when.

**Comment by dpshelio** [comment]
_From @gmlaghari on March 3, 2016 10:7_

@Cadair Try it when you get time. I am stuck here little here. Although SunPy is giving error, but plotting spectrogram without colorbar. 
Your effort is highly appreciated.

**Comment by dpshelio** [comment]
_From @gmlaghari on March 8, 2016 4:59_

@Cadair Any progress? I am getting same error even on older version.

**Comment by dpshelio** [comment]
_From @gmlaghari on July 28, 2016 7:47_

@Cadair How to add colorbar in Sunpy spectrogram map?

**Comment by dpshelio** [comment]
_From @agneet42 on March 30, 2017 12:48_

@Cadair with Python3 and Matplotlib 2.0, I get this image with the given fits file. 
![ ](https://github.com/agneet42/sunpy_images/blob/master/Image1.jpg)

Does this still count as an error?

**Comment by dpshelio** [comment]
_From @Cadair on March 30, 2017 12:51_

looks like this could be a python 2 specific unicode error from the original traceback.

**Comment by dpshelio** [comment]
_From @agneet42 on March 30, 2017 12:59_

If the default encoding of Python is utf8, I guess this error won't come across?

**Comment by nabobalis** [comment]
Deleted Spectrogram class and started again.
