### ISSUE TITLE
radiospectra.sources.callisto - failing to open eCallisto files with incorrectly formatted end time 

### ISSUE THREAD

**Issue by lukas-hoefig** [sunpy/radiospectra#74]
### Describe the bug

eCallisto provides fits files that can have an incorrect timestamp (this happens with files created at 23:45:00 and after), which [radiospectra.sources.callisto  CallistoSpectrogram read() ]
tries to open, but doesnt factcheck the timestamp

ValueError: Input values did not match any of the formats where the format keyword is optional: {'datetime': TypeError('Input values for datetime class must be datetime objects'), 'ymdhms': ValueError('input must be dict or table-like'), 'iso': ValueError('Time 2022/01/01T24:00:06 does not match iso format'), 'isot': ValueError('**Time 2022/01/01T24:00:06** does not match isot format'), 'yday': ValueError('Time 2022/01/01T24:00:06 does not match yday format'), 'datetime64': TypeError('Input values for datetime64 class must be datetime64 objects'), 'fits': ValueError('Time 2022/01/01T24:00:06 does not match fits format'), 'byear_str': ValueError('Time 2022/01/01T24:00:06 does not match byear_str format'), 'jyear_str': ValueError('Time 2022/01/01T24:00:06 does not match jyear_str format'), 'astropy_time': TypeError('Input values for astropy_time class must all be same astropy Time type.')}

### To Reproduce
```
from radiospectra.sources.callisto import CallistoSpectrogram
import radiospectra.sources.callisto as cal
from astropy.io import fits
from datetime import datetime

time = datetime(2022,1,1,23,48)
station = "KASI"

url_list = cal.query(time, time, [station])
cal.download(url_list, "./")

file = "./KASI_20220101_234506_59.fit.gz"

with fits.open(file) as open_file:
    print(f'start: {open_file[0].header["DATE-OBS"]} {open_file[0].header["TIME-OBS"]}')
    print(f'end:   {open_file[0].header["DATE-END"]} {open_file[0].header["TIME-END"]}')

fail_to_open = CallistoSpectrogram.read(file)
```

### System Details

Python version 3.8 , 3.9 
Windows and Linux 
radiospectra==0.3.0
sunpy==3.1.3

### Installation method

pip

**Comment by nabobalis** [comment]
Thanks for the report, do you happen to have a URL so I can download the file?

**Comment by nabobalis** [comment]
Thanks, I will investigate and see if I can work out how to fix it.

**Comment by samaloney** [comment]
Hum ok I guess need to add a try catch around parsing the date and then look for a 24th hour 😆 from e.g `2022/01/01T24:00:06`

**Comment by samaloney** [comment]
So once #84 is merged this should be fixed. There has been a significant change to radiospectra so I've included update code for the example above here.

```python
from matplotlib import pyplot as plt
from sunpy.net import Fido, attrs as a

from radiospectra import net
from radiospectra.net import attrs as ra
from radiospectra.spectrogram import Spectrogram

query = Fido.search(a.Time('2022-01-01T23:45', '2022-01-01T23:59'), 
                                   a.Instrument.ecallisto, ra.Observatory('KASI'))
query
# <sunpy.net.fido_factory.UnifiedResponse object at 0x11ce42550>
# Results from 1 Provider:
# 
# 1 Results from the CALLISTOClient:
# 
#        Start Time               End Time         Provider Instrument Observatory  ID
# ----------------------- ----------------------- --------- ---------- ----------- ---
# 2022-01-01 23:45:06.000 2022-01-02 00:00:05.999 ECALLISTO  ECALLISTO        KASI  59
file = Fido.fetch(query)
spec = Spectrogram(file[0])
spec.plot()
plt.show()
```

![rs-kasi](https://user-images.githubusercontent.com/24570854/201865786-1590f087-426a-454d-9be7-0d1bdf0bfd3a.png)

**Comment by samaloney** [comment]
With the current version of the software this is still an issue

```
from sunpy.net import Fido, attrs as a

from radiospectra import net
from radiospectra.net import attrs as ra
from radiospectra.spectrogram import Spectrogram

query = Fido.search(a.Time('2022-01-01T23:45', '2022-01-01T23:59'),
                    a.Instrument.ecallisto, ra.Observatory('KASI'))
query
<sunpy.net.fido_factory.UnifiedResponse object at 0x10bc4d370>
Results from 1 Provider:

1 Results from the CALLISTOClient:

       Start Time               End Time         Provider Instrument Observatory  ID
----------------------- ----------------------- --------- ---------- ----------- ---
2022-01-01 23:45:06.000 2022-01-02 00:00:05.999 ECALLISTO  ECALLISTO        KASI  59

file = Fido.fetch(query)
spec = Spectrogram(file[0])
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
...
```
