### ISSUE TITLE
Spectrogram  Attributes not Documented Well

### ISSUE THREAD

**Issue by dpshelio** [sunpy/radiospectra#9]
_From @prateekiiest on March 10, 2017 13:48_

Some of the documentation is not clear in http://docs.sunpy.org/en/stable/generated/api/sunpy.spectra.spectrogram.Spectrogram.html

in the attribute section table, like for `COPY_Properties` and `shape`.

Also there is some mismatch in the font.

_Copied from original issue: sunpy/sunpy#2033_

**Comment by dpshelio** [comment]
_From @prateekiiest on March 10, 2017 13:48_

I will be sending a PR regarding this

**Comment by nabobalis** [comment]
Deleted Spectrogram class and started again.
